---
- hosts: all
  sudo: true

  vars:
    nodejs_version: "0.12"
    nodejs_npm_global_packages:
      - name: npm
        version: 2.11.3

  environment:
    NODE_CONFIG_DIR: /opt/isomorphic-frontend-framework/config/
    NODE_ENV: production
    
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: redis, tags: redis }

  tasks:
    - include: tasks/main.yml
